/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import com.sun.glass.ui.Cursor;
import com.sun.webkit.dom.EventImpl;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.net.URL;
import javax.swing.JOptionPane;

/**
 *
 * @author IdeaSofist
 */
public class ViewHome extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public ViewHome() {
        initComponents();
        setaricon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bSair = new javax.swing.JPanel();
        bCadastro = new javax.swing.JPanel();
        bFinanceiro = new javax.swing.JPanel();
        bNovaOs = new javax.swing.JPanel();
        bOs = new javax.swing.JPanel();
        bPdv = new javax.swing.JPanel();
        bCaixa = new javax.swing.JPanel();
        bClientes = new javax.swing.JPanel();
        bProdutos = new javax.swing.JPanel();
        bEstoque = new javax.swing.JPanel();
        bSobre = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setType(java.awt.Window.Type.UTILITY);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bSair.setOpaque(false);
        bSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSairMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bSairLayout = new javax.swing.GroupLayout(bSair);
        bSair.setLayout(bSairLayout);
        bSairLayout.setHorizontalGroup(
            bSairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 85, Short.MAX_VALUE)
        );
        bSairLayout.setVerticalGroup(
            bSairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(bSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 510, 85, 40));

        bCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bCadastro.setOpaque(false);
        bCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bCadastroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bCadastroLayout = new javax.swing.GroupLayout(bCadastro);
        bCadastro.setLayout(bCadastroLayout);
        bCadastroLayout.setHorizontalGroup(
            bCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        bCadastroLayout.setVerticalGroup(
            bCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(bCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 380, 40));

        bFinanceiro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bFinanceiro.setOpaque(false);
        bFinanceiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bFinanceiroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bFinanceiroLayout = new javax.swing.GroupLayout(bFinanceiro);
        bFinanceiro.setLayout(bFinanceiroLayout);
        bFinanceiroLayout.setHorizontalGroup(
            bFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        bFinanceiroLayout.setVerticalGroup(
            bFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(bFinanceiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, -1, 40));

        bNovaOs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bNovaOs.setOpaque(false);
        bNovaOs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bNovaOsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bNovaOsLayout = new javax.swing.GroupLayout(bNovaOs);
        bNovaOs.setLayout(bNovaOsLayout);
        bNovaOsLayout.setHorizontalGroup(
            bNovaOsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        bNovaOsLayout.setVerticalGroup(
            bNovaOsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(bNovaOs, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 340, 30));

        bOs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bOs.setOpaque(false);
        bOs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bOsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bOsLayout = new javax.swing.GroupLayout(bOs);
        bOs.setLayout(bOsLayout);
        bOsLayout.setHorizontalGroup(
            bOsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        bOsLayout.setVerticalGroup(
            bOsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(bOs, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 340, 40));

        bPdv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bPdv.setOpaque(false);
        bPdv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bPdvMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bPdvLayout = new javax.swing.GroupLayout(bPdv);
        bPdv.setLayout(bPdvLayout);
        bPdvLayout.setHorizontalGroup(
            bPdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        bPdvLayout.setVerticalGroup(
            bPdvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(bPdv, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 340, 30));

        bCaixa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bCaixa.setOpaque(false);
        bCaixa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bCaixaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bCaixaLayout = new javax.swing.GroupLayout(bCaixa);
        bCaixa.setLayout(bCaixaLayout);
        bCaixaLayout.setHorizontalGroup(
            bCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        bCaixaLayout.setVerticalGroup(
            bCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(bCaixa, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, 350, 40));

        bClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bClientes.setOpaque(false);
        bClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bClientesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bClientesLayout = new javax.swing.GroupLayout(bClientes);
        bClientes.setLayout(bClientesLayout);
        bClientesLayout.setHorizontalGroup(
            bClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        bClientesLayout.setVerticalGroup(
            bClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        getContentPane().add(bClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 350, 32));

        bProdutos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bProdutos.setOpaque(false);
        bProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bProdutosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bProdutosLayout = new javax.swing.GroupLayout(bProdutos);
        bProdutos.setLayout(bProdutosLayout);
        bProdutosLayout.setHorizontalGroup(
            bProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        bProdutosLayout.setVerticalGroup(
            bProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(bProdutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, 350, 40));

        bEstoque.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bEstoque.setOpaque(false);
        bEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bEstoqueMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bEstoqueLayout = new javax.swing.GroupLayout(bEstoque);
        bEstoque.setLayout(bEstoqueLayout);
        bEstoqueLayout.setHorizontalGroup(
            bEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        bEstoqueLayout.setVerticalGroup(
            bEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        getContentPane().add(bEstoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 380, 45));

        bSobre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bSobre.setOpaque(false);
        bSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSobreMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bSobreLayout = new javax.swing.GroupLayout(bSobre);
        bSobre.setLayout(bSobreLayout);
        bSobreLayout.setHorizontalGroup(
            bSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        bSobreLayout.setVerticalGroup(
            bSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        getContentPane().add(bSobre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 371, 380, 45));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TelaHome.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_Z){
            final ViewLoading carregando = new ViewLoading();
        carregando.setVisible(true);
        Thread t = new Thread() {

            public void run() {

                try {

                    // métodos
                    ViewOs os = new ViewOs();
                    os.setVisible(true);

                    carregando.dispose();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                    carregando.dispose();
                }
            }
        };
        t.start();

        }
        
    }//GEN-LAST:event_formKeyReleased

    private void bSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSairMouseClicked
        // TODO add your handling code here:
        int confirma = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja Sair?", "Atenção!", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_bSairMouseClicked

    private void bNovaOsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bNovaOsMouseClicked
        // TODO add your handling code here:
        ViewOs os  = new ViewOs();
        
        // Início Carregamento
        final ViewLoading carregando = new ViewLoading();
            carregando.setVisible(true);
            Thread t = new Thread() {

                public void run() {

                    try {
                        
                        // Métodos
                        os.setVisible(true);
                        
                        carregando.dispose();
                         
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                        carregando.dispose();
                    }
                }
            };
            t.start();
        // FIM Carregamento
    }//GEN-LAST:event_bNovaOsMouseClicked

    private void bCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCadastroMouseClicked
        // TODO add your handling code here:
        
        ViewCadastro cadastro = new ViewCadastro();
        
        // Início Carregamento
        final ViewLoading carregando = new ViewLoading();
            carregando.setVisible(true);
            Thread t = new Thread() {

                public void run() {

                    try {
                        
                        // Métodos
                        cadastro.setVisible(true);
                        
                        carregando.dispose();
                        
                         
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                        carregando.dispose();
                    }
                }
            };
            t.start();
        // FIM Carregamento
        
    }//GEN-LAST:event_bCadastroMouseClicked

    private void bFinanceiroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bFinanceiroMouseClicked
        // TODO add your handling code here:
        
        //ViewFinanceiro financeiro = new ViewFinanceiro();
        ViewAcessoFinanceiro acesso = new ViewAcessoFinanceiro();
        // Início Carregamento
        final ViewLoading carregando = new ViewLoading();
            carregando.setVisible(true);
            Thread t = new Thread() {

                public void run() {

                    try {
                        
                        // Métodos
                        //java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.WAIT_CURSOR);
                        acesso.setVisible(true);
                         
                        carregando.dispose();
                         
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                        carregando.dispose();
                    }
                }
            };
            t.start();
        // FIM Carregamento
        
    }//GEN-LAST:event_bFinanceiroMouseClicked

    private void bOsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bOsMouseClicked
        // TODO add your handling code here:
        //ViewFinanceiro financeiro = new ViewFinanceiro();
        ViewOsCadastradas os = new ViewOsCadastradas();
        // Início Carregamento
        final ViewLoading carregando = new ViewLoading();
            carregando.setVisible(true);
            Thread t = new Thread() {

                public void run() {

                    try {
                        
                        // Métodos
                         
                        os.setVisible(true);
                        
                        carregando.dispose();
                         
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                        carregando.dispose();
                    }
                }
            };
            t.start();
        // FIM Carregamento
    }//GEN-LAST:event_bOsMouseClicked

    private void bPdvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPdvMouseClicked
        // TODO add your handling code here:
        
        
         ViewPdv pdv = new ViewPdv();
        
        // Início Carregamento
        final ViewLoading carregando = new ViewLoading();
            carregando.setVisible(true);
            Thread t = new Thread() {

                public void run() {

                    try {
                        
                        // Métodos
                        pdv.setVisible(true);
                        
                        carregando.dispose();
                         
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                        carregando.dispose();
                    }
                }
            };
            t.start();
        // FIM Carregamento
        
        
    }//GEN-LAST:event_bPdvMouseClicked

    private void bCaixaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCaixaMouseClicked
        // TODO add your handling code here:
        ViewCaixa caixa = new ViewCaixa();
        
        // Início Carregamento
        final ViewLoading carregando = new ViewLoading();
            carregando.setVisible(true);
            Thread t = new Thread() {

                public void run() {

                    try {
                        
                        // Métodos
                        caixa.setVisible(true);
                        
                        carregando.dispose();
                         
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                        carregando.dispose();
                    }
                }
            };
            t.start();
        // FIM Carregamento
        
        
    }//GEN-LAST:event_bCaixaMouseClicked

    private void bClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bClientesMouseClicked
        // TODO add your handling code here:
         ViewClientesCadastrados clientes = new ViewClientesCadastrados();
        
        // Início Carregamento
        final ViewLoading carregando = new ViewLoading();
            carregando.setVisible(true);
            Thread t = new Thread() {

                public void run() {

                    try {
                        
                        // Métodos
                        clientes.setVisible(true);
                        
                        carregando.dispose();
                         
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                        carregando.dispose();
                    }
                }
            };
            t.start();
        // FIM Carregamento
        
    }//GEN-LAST:event_bClientesMouseClicked

    private void bProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bProdutosMouseClicked
        // TODO add your handling code here:
        ViewProdutosCadastrados produtos = new ViewProdutosCadastrados();
        
        // Início Carregamento
        final ViewLoading carregando = new ViewLoading();
            carregando.setVisible(true);
            Thread t = new Thread() {

                public void run() {

                    try {
                        
                        // Métodos
                        produtos.setVisible(true);
                        
                        carregando.dispose();
                         
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                        carregando.dispose();
                    }
                }
            };
            t.start();
        // FIM Carregamento
    }//GEN-LAST:event_bProdutosMouseClicked

    private void bEstoqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bEstoqueMouseClicked
        // TODO add your handling code here:
        ViewEstoque estoque = new ViewEstoque();
        
        // Início Carregamento
        final ViewLoading carregando = new ViewLoading();
            carregando.setVisible(true);
            Thread t = new Thread() {

                public void run() {

                    try {
                        
                        // Métodos
                        estoque.setVisible(true);
                        
                        carregando.dispose();
                         
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                        carregando.dispose();
                    }
                }
            };
            t.start();
        // FIM Carregamento
        
    }//GEN-LAST:event_bEstoqueMouseClicked

    private void bSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSobreMouseClicked
        // TODO add your handling code here:
         ViewSobre sobre = new ViewSobre();
        
        // Início Carregamento
        final ViewLoading carregando = new ViewLoading();
            carregando.setVisible(true);
            Thread t = new Thread() {

                public void run() {

                    try {
                        
                        // Métodos
                        sobre.setVisible(true);
                        
                        carregando.dispose();
                         
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                        carregando.dispose();
                    }
                }
            };
            t.start();
        // FIM Carregamento
        
    }//GEN-LAST:event_bSobreMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bCadastro;
    private javax.swing.JPanel bCaixa;
    private javax.swing.JPanel bClientes;
    private javax.swing.JPanel bEstoque;
    private javax.swing.JPanel bFinanceiro;
    private javax.swing.JPanel bNovaOs;
    private javax.swing.JPanel bOs;
    private javax.swing.JPanel bPdv;
    private javax.swing.JPanel bProdutos;
    private javax.swing.JPanel bSair;
    private javax.swing.JPanel bSobre;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    
    // INÍCIO Método para setar icon do jFrame
    private void setaricon() {

        //  ImageIcon frameIcon = new ImageIcon("icon.png");
        //this.setIconImage(frameIcon.getImage());
        URL url = this.getClass().getResource("icon.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
    }
    // FIM Método para setar icon do jFrame
 
}
