/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import javax.swing.JOptionPane;

/**
 *
 * @author IdeaSofist
 */
public class ViewCadastro extends javax.swing.JFrame {

    /**
     * Creates new form ViewCadastro
     */
    public ViewCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bSair = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        bFinanceiro = new javax.swing.JPanel();
        bCadastrarCliente = new javax.swing.JPanel();
        bCadastroProdutos = new javax.swing.JPanel();
        bCadastroUsuarios = new javax.swing.JPanel();
        bEstoque = new javax.swing.JPanel();
        bSobre = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bSair.setOpaque(false);
        bSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSairMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bSairLayout = new javax.swing.GroupLayout(bSair);
        bSair.setLayout(bSairLayout);
        bSairLayout.setHorizontalGroup(
            bSairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 85, Short.MAX_VALUE)
        );
        bSairLayout.setVerticalGroup(
            bSairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(bSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 510, 85, 40));

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.setOpaque(false);
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 380, 50));

        bFinanceiro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bFinanceiro.setOpaque(false);
        bFinanceiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bFinanceiroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bFinanceiroLayout = new javax.swing.GroupLayout(bFinanceiro);
        bFinanceiro.setLayout(bFinanceiroLayout);
        bFinanceiroLayout.setHorizontalGroup(
            bFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        bFinanceiroLayout.setVerticalGroup(
            bFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(bFinanceiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 380, 40));

        bCadastrarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bCadastrarCliente.setOpaque(false);
        bCadastrarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bCadastrarClienteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bCadastrarClienteLayout = new javax.swing.GroupLayout(bCadastrarCliente);
        bCadastrarCliente.setLayout(bCadastrarClienteLayout);
        bCadastrarClienteLayout.setHorizontalGroup(
            bCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );
        bCadastrarClienteLayout.setVerticalGroup(
            bCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(bCadastrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 270, 40));

        bCadastroProdutos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bCadastroProdutos.setOpaque(false);
        bCadastroProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bCadastroProdutosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bCadastroProdutosLayout = new javax.swing.GroupLayout(bCadastroProdutos);
        bCadastroProdutos.setLayout(bCadastroProdutosLayout);
        bCadastroProdutosLayout.setHorizontalGroup(
            bCadastroProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );
        bCadastroProdutosLayout.setVerticalGroup(
            bCadastroProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(bCadastroProdutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 275, 270, 40));

        bCadastroUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bCadastroUsuarios.setOpaque(false);
        bCadastroUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bCadastroUsuariosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bCadastroUsuariosLayout = new javax.swing.GroupLayout(bCadastroUsuarios);
        bCadastroUsuarios.setLayout(bCadastroUsuariosLayout);
        bCadastroUsuariosLayout.setHorizontalGroup(
            bCadastroUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
        );
        bCadastroUsuariosLayout.setVerticalGroup(
            bCadastroUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        getContentPane().add(bCadastroUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 361, 273, 45));

        bEstoque.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bEstoque.setOpaque(false);
        bEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bEstoqueMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bEstoqueLayout = new javax.swing.GroupLayout(bEstoque);
        bEstoque.setLayout(bEstoqueLayout);
        bEstoqueLayout.setHorizontalGroup(
            bEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        bEstoqueLayout.setVerticalGroup(
            bEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(bEstoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 323, 380, 40));

        bSobre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bSobre.setOpaque(false);
        bSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSobreMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bSobreLayout = new javax.swing.GroupLayout(bSobre);
        bSobre.setLayout(bSobreLayout);
        bSobreLayout.setHorizontalGroup(
            bSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        bSobreLayout.setVerticalGroup(
            bSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        getContentPane().add(bSobre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 371, 380, 45));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TelaCadastro.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSairMouseClicked
        // TODO add your handling code here:
        int confirma = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja Sair?", "Atenção!", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_bSairMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        ViewHome home = new ViewHome();
        // Início Carregamento
        final ViewLoading carregando = new ViewLoading();
            carregando.setVisible(true);
            Thread t = new Thread() {

                public void run() {

                    try {
                        
                        // Métodos
                        home.setVisible(true);
                        
                        carregando.dispose();
                         
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                        carregando.dispose();
                    }
                }
            };
            t.start();
        // FIM Carregamento
    }//GEN-LAST:event_jPanel1MouseClicked

    private void bFinanceiroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bFinanceiroMouseClicked
        // TODO add your handling code here:
        //ViewFinanceiro financeiro = new ViewFinanceiro();
        ViewAcessoFinanceiro acesso = new ViewAcessoFinanceiro();
        // Início Carregamento
        final ViewLoading carregando = new ViewLoading();
            carregando.setVisible(true);
            Thread t = new Thread() {

                public void run() {

                    try {
                        
                        // Métodos
                         
                        acesso.setVisible(true);
                        
                        carregando.dispose();
                         
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                        carregando.dispose();
                    }
                }
            };
            t.start();
        // FIM Carregamento
    }//GEN-LAST:event_bFinanceiroMouseClicked

    private void bCadastrarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCadastrarClienteMouseClicked
        // TODO add your handling code here:
        ViewNovoCliente novoCliente = new ViewNovoCliente();
        // Início Carregamento
        final ViewLoading carregando = new ViewLoading();
            carregando.setVisible(true);
            Thread t = new Thread() {

                public void run() {

                    try {
                        
                        // Métodos
                        novoCliente.setVisible(true);
                        
                        carregando.dispose();
                         
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                        carregando.dispose();
                    }
                }
            };
            t.start();
        // FIM Carregamento
    }//GEN-LAST:event_bCadastrarClienteMouseClicked

    private void bCadastroProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCadastroProdutosMouseClicked
        // TODO add your handling code here:
        
        ViewAcessoCadastroProdutos produtos = new ViewAcessoCadastroProdutos();
        // Início Carregamento
        final ViewLoading carregando = new ViewLoading();
            carregando.setVisible(true);
            Thread t = new Thread() {

                public void run() {

                    try {
                        
                        // Métodos
                        produtos.setVisible(true);
                        
                        carregando.dispose();
                         
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                        carregando.dispose();
                    }
                }
            };
            t.start();
        // FIM Carregamento
        
        
    }//GEN-LAST:event_bCadastroProdutosMouseClicked

    private void bCadastroUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCadastroUsuariosMouseClicked
        // TODO add your handling code here:
        
        ViewAcessoCadastroUsuarios usuarios = new ViewAcessoCadastroUsuarios();
        // Início Carregamento
        final ViewLoading carregando = new ViewLoading();
            carregando.setVisible(true);
            Thread t = new Thread() {

                public void run() {

                    try {
                        
                        // Métodos
                        usuarios.setVisible(true);
                        
                        carregando.dispose();
                         
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                        carregando.dispose();
                    }
                }
            };
            t.start();
        // FIM Carregamento
        
        
    }//GEN-LAST:event_bCadastroUsuariosMouseClicked

    private void bEstoqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bEstoqueMouseClicked
        // TODO add your handling code here:
         ViewEstoque estoque = new ViewEstoque();
        
        // Início Carregamento
        final ViewLoading carregando = new ViewLoading();
            carregando.setVisible(true);
            Thread t = new Thread() {

                public void run() {

                    try {
                        
                        // Métodos
                        estoque.setVisible(true);
                        
                        carregando.dispose();
                         
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                        carregando.dispose();
                    }
                }
            };
            t.start();
        // FIM Carregamento
    }//GEN-LAST:event_bEstoqueMouseClicked

    private void bSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSobreMouseClicked
        // TODO add your handling code here:
        ViewSobre sobre = new ViewSobre();

        // Início Carregamento
        final ViewLoading carregando = new ViewLoading();
        carregando.setVisible(true);
        Thread t = new Thread() {

            public void run() {

                try {

                    // Métodos
                    sobre.setVisible(true);

                    carregando.dispose();

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                    carregando.dispose();
                }
            }
        };
        t.start();
        // FIM Carregamento
    }//GEN-LAST:event_bSobreMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bCadastrarCliente;
    private javax.swing.JPanel bCadastroProdutos;
    private javax.swing.JPanel bCadastroUsuarios;
    private javax.swing.JPanel bEstoque;
    private javax.swing.JPanel bFinanceiro;
    private javax.swing.JPanel bSair;
    private javax.swing.JPanel bSobre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
