/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.JOptionPane;

/**
 *
 * @author IdeaSofist
 */
public class ViewSobre extends javax.swing.JFrame {

    /**
     * Creates new form ViewSobre
     */
    public ViewSobre() {
        initComponents();
        setaricon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bFinanceiro = new javax.swing.JPanel();
        bCadastro = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        bHome = new javax.swing.JPanel();
        bSair = new javax.swing.JPanel();
        bCadastro1 = new javax.swing.JPanel();
        bFinanceiro1 = new javax.swing.JPanel();
        bEstoque = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bFinanceiro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bFinanceiro.setOpaque(false);
        bFinanceiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bFinanceiroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bFinanceiroLayout = new javax.swing.GroupLayout(bFinanceiro);
        bFinanceiro.setLayout(bFinanceiroLayout);
        bFinanceiroLayout.setHorizontalGroup(
            bFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        bFinanceiroLayout.setVerticalGroup(
            bFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(bFinanceiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, -1, 40));

        bCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bCadastro.setOpaque(false);
        bCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bCadastroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bCadastroLayout = new javax.swing.GroupLayout(bCadastro);
        bCadastro.setLayout(bCadastroLayout);
        bCadastroLayout.setHorizontalGroup(
            bCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        bCadastroLayout.setVerticalGroup(
            bCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(bCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 380, 40));

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.setOpaque(false);
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 380, 45));

        bHome.setToolTipText(""); // NOI18N
        bHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bHome.setOpaque(false);
        bHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bHomeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bHomeLayout = new javax.swing.GroupLayout(bHome);
        bHome.setLayout(bHomeLayout);
        bHomeLayout.setHorizontalGroup(
            bHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        bHomeLayout.setVerticalGroup(
            bHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(bHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 380, 50));

        bSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bSair.setOpaque(false);
        bSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSairMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bSairLayout = new javax.swing.GroupLayout(bSair);
        bSair.setLayout(bSairLayout);
        bSairLayout.setHorizontalGroup(
            bSairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        bSairLayout.setVerticalGroup(
            bSairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(bSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 510, 90, 40));

        bCadastro1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bCadastro1.setOpaque(false);
        bCadastro1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bCadastro1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bCadastro1Layout = new javax.swing.GroupLayout(bCadastro1);
        bCadastro1.setLayout(bCadastro1Layout);
        bCadastro1Layout.setHorizontalGroup(
            bCadastro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        bCadastro1Layout.setVerticalGroup(
            bCadastro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(bCadastro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 380, 40));

        bFinanceiro1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bFinanceiro1.setOpaque(false);
        bFinanceiro1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bFinanceiro1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bFinanceiro1Layout = new javax.swing.GroupLayout(bFinanceiro1);
        bFinanceiro1.setLayout(bFinanceiro1Layout);
        bFinanceiro1Layout.setHorizontalGroup(
            bFinanceiro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        bFinanceiro1Layout.setVerticalGroup(
            bFinanceiro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(bFinanceiro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, -1, 40));

        bEstoque.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bEstoque.setOpaque(false);
        bEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bEstoqueMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bEstoqueLayout = new javax.swing.GroupLayout(bEstoque);
        bEstoque.setLayout(bEstoqueLayout);
        bEstoqueLayout.setHorizontalGroup(
            bEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        bEstoqueLayout.setVerticalGroup(
            bEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        getContentPane().add(bEstoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 380, 45));

        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.setOpaque(false);
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 380, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TelaSobre.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCadastroMouseClicked
        // TODO add your handling code here:

        ViewCadastro cadastro = new ViewCadastro();

        // Início Carregamento
        final ViewLoading carregando = new ViewLoading();
        carregando.setVisible(true);
        Thread t = new Thread() {

            public void run() {

                try {

                    // Métodos
                    cadastro.setVisible(true);

                    carregando.dispose();

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                    carregando.dispose();
                }
            }
        };
        t.start();
        // FIM Carregamento
    }//GEN-LAST:event_bCadastroMouseClicked

    private void bFinanceiroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bFinanceiroMouseClicked
        // TODO add your handling code here:

        //ViewFinanceiro financeiro = new ViewFinanceiro();
        ViewAcessoFinanceiro acesso = new ViewAcessoFinanceiro();
        // Início Carregamento
        final ViewLoading carregando = new ViewLoading();
        carregando.setVisible(true);
        Thread t = new Thread() {

            public void run() {

                try {

                    // Métodos
                    //java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.WAIT_CURSOR);
                    acesso.setVisible(true);

                    carregando.dispose();

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                    carregando.dispose();
                }
            }
        };
        t.start();
        // FIM Carregamento
    }//GEN-LAST:event_bFinanceiroMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        ViewEstoque estoque = new ViewEstoque();

        // Início Carregamento
        final ViewLoading carregando = new ViewLoading();
        carregando.setVisible(true);
        Thread t = new Thread() {

            public void run() {

                try {

                    // Métodos
                    estoque.setVisible(true);

                    carregando.dispose();

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                    carregando.dispose();
                }
            }
        };
        t.start();
        // FIM Carregamento
    }//GEN-LAST:event_jPanel1MouseClicked

    private void bHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bHomeMouseClicked
        // TODO add your handling code here:
        ViewHome home = new ViewHome();

        // Início Carregamento
        final ViewLoading carregando = new ViewLoading();
        carregando.setVisible(true);
        Thread t = new Thread() {

            public void run() {

                try {

                    // Métodos
                    home.setVisible(true);

                    carregando.dispose();

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                    carregando.dispose();
                }
            }
        };
        t.start();
        // FIM Carregamento
    }//GEN-LAST:event_bHomeMouseClicked

    private void bSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSairMouseClicked
        // TODO add your handling code here:
        int confirma = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja Sair?", "Atenção!", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_bSairMouseClicked

    private void bCadastro1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCadastro1MouseClicked
        // TODO add your handling code here:

        ViewCadastro cadastro = new ViewCadastro();

        // Início Carregamento
        final ViewLoading carregando = new ViewLoading();
        carregando.setVisible(true);
        Thread t = new Thread() {

            public void run() {

                try {

                    // Métodos
                    cadastro.setVisible(true);

                    carregando.dispose();

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                    carregando.dispose();
                }
            }
        };
        t.start();
        // FIM Carregamento
    }//GEN-LAST:event_bCadastro1MouseClicked

    private void bFinanceiro1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bFinanceiro1MouseClicked
        // TODO add your handling code here:

        //ViewFinanceiro financeiro = new ViewFinanceiro();
        ViewAcessoFinanceiro acesso = new ViewAcessoFinanceiro();
        // Início Carregamento
        final ViewLoading carregando = new ViewLoading();
        carregando.setVisible(true);
        Thread t = new Thread() {

            public void run() {

                try {

                    // Métodos
                    //java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.WAIT_CURSOR);
                    acesso.setVisible(true);

                    carregando.dispose();

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                    carregando.dispose();
                }
            }
        };
        t.start();
        // FIM Carregamento
    }//GEN-LAST:event_bFinanceiro1MouseClicked

    private void bEstoqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bEstoqueMouseClicked
        // TODO add your handling code here:
        ViewEstoque estoque = new ViewEstoque();

        // Início Carregamento
        final ViewLoading carregando = new ViewLoading();
        carregando.setVisible(true);
        Thread t = new Thread() {

            public void run() {

                try {

                    // Métodos
                    estoque.setVisible(true);

                    carregando.dispose();

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                    carregando.dispose();
                }
            }
        };
        t.start();
        // FIM Carregamento
    }//GEN-LAST:event_bEstoqueMouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        ViewHome home = new ViewHome();
        // Início Carregamento
        final ViewLoading carregando = new ViewLoading();
        carregando.setVisible(true);
        Thread t = new Thread() {

            public void run() {

                try {

                    // Métodos
                    home.setVisible(true);

                    carregando.dispose();

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                    carregando.dispose();
                }
            }
        };
        t.start();
        // FIM Carregamento
    }//GEN-LAST:event_jPanel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewSobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewSobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewSobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewSobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewSobre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bCadastro;
    private javax.swing.JPanel bCadastro1;
    private javax.swing.JPanel bEstoque;
    private javax.swing.JPanel bFinanceiro;
    private javax.swing.JPanel bFinanceiro1;
    private javax.swing.JPanel bHome;
    private javax.swing.JPanel bSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables


// INÍCIO Método para setar icon do jFrame
    private void setaricon() {

        //  ImageIcon frameIcon = new ImageIcon("icon.png");
        //this.setIconImage(frameIcon.getImage());
        URL url = this.getClass().getResource("icon.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
    }
    // FIM Método para setar icon do jFrame


}
