/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import dao.ConnectionFactory;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author IdeaSofist
 */
public class ViewEstoque extends javax.swing.JFrame {

    /**
     * Creates new form ViewEstoque
     */
    public ViewEstoque() {
        initComponents();
        setaricon();
        listarProdutos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbProdutos = new javax.swing.JTable();
        bSair = new javax.swing.JPanel();
        bHome = new javax.swing.JPanel();
        bCadastro = new javax.swing.JPanel();
        bFinanceiro = new javax.swing.JPanel();
        bSobre = new javax.swing.JPanel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbProdutos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 620, 360));

        bSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bSair.setOpaque(false);
        bSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSairMouseClicked(evt);
            }
        });
        getContentPane().add(bSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 510, 80, 40));

        bHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bHome.setOpaque(false);
        bHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bHomeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bHomeLayout = new javax.swing.GroupLayout(bHome);
        bHome.setLayout(bHomeLayout);
        bHomeLayout.setHorizontalGroup(
            bHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        bHomeLayout.setVerticalGroup(
            bHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(bHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 380, 50));

        bCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bCadastro.setOpaque(false);
        bCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bCadastroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bCadastroLayout = new javax.swing.GroupLayout(bCadastro);
        bCadastro.setLayout(bCadastroLayout);
        bCadastroLayout.setHorizontalGroup(
            bCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        bCadastroLayout.setVerticalGroup(
            bCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(bCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 380, 40));

        bFinanceiro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bFinanceiro.setOpaque(false);
        bFinanceiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bFinanceiroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bFinanceiroLayout = new javax.swing.GroupLayout(bFinanceiro);
        bFinanceiro.setLayout(bFinanceiroLayout);
        bFinanceiroLayout.setHorizontalGroup(
            bFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        bFinanceiroLayout.setVerticalGroup(
            bFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(bFinanceiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 380, 40));

        bSobre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bSobre.setOpaque(false);
        bSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSobreMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bSobreLayout = new javax.swing.GroupLayout(bSobre);
        bSobre.setLayout(bSobreLayout);
        bSobreLayout.setHorizontalGroup(
            bSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        bSobreLayout.setVerticalGroup(
            bSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        getContentPane().add(bSobre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 371, 380, 45));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TelaEstoque.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSairMouseClicked
        // TODO add your handling code here:
       int confirma = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja Sair?", "Atenção!", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_bSairMouseClicked

    private void bHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bHomeMouseClicked
        // TODO add your handling code here:
        ViewHome home = new ViewHome();
        // Início Carregamento
        final ViewLoading carregando = new ViewLoading();
        carregando.setVisible(true);
        Thread t = new Thread() {

            public void run() {

                try {

                    // Métodos
                    home.setVisible(true);

                    carregando.dispose();

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                    carregando.dispose();
                }
            }
        };
        t.start();
        // FIM Carregamento
    }//GEN-LAST:event_bHomeMouseClicked

    private void bCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCadastroMouseClicked
        // TODO add your handling code here:

        ViewCadastro cadastro = new ViewCadastro();

        // Início Carregamento
        final ViewLoading carregando = new ViewLoading();
        carregando.setVisible(true);
        Thread t = new Thread() {

            public void run() {

                try {

                    // Métodos
                    cadastro.setVisible(true);

                    carregando.dispose();

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                    carregando.dispose();
                }
            }
        };
        t.start();
        // FIM Carregamento
    }//GEN-LAST:event_bCadastroMouseClicked

    private void bFinanceiroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bFinanceiroMouseClicked
        // TODO add your handling code here:
        //ViewFinanceiro financeiro = new ViewFinanceiro();
        ViewAcessoFinanceiro acesso = new ViewAcessoFinanceiro();
        // Início Carregamento
        final ViewLoading carregando = new ViewLoading();
        carregando.setVisible(true);
        Thread t = new Thread() {

            public void run() {

                try {

                    // Métodos

                    acesso.setVisible(true);

                    carregando.dispose();

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                    carregando.dispose();
                }
            }
        };
        t.start();
        // FIM Carregamento
    }//GEN-LAST:event_bFinanceiroMouseClicked

    private void bSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSobreMouseClicked
        // TODO add your handling code here:
        ViewSobre sobre = new ViewSobre();

        // Início Carregamento
        final ViewLoading carregando = new ViewLoading();
        carregando.setVisible(true);
        Thread t = new Thread() {

            public void run() {

                try {

                    // Métodos
                    sobre.setVisible(true);

                    carregando.dispose();

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                    carregando.dispose();
                }
            }
        };
        t.start();
        // FIM Carregamento
    }//GEN-LAST:event_bSobreMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewEstoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bCadastro;
    private javax.swing.JPanel bFinanceiro;
    private javax.swing.JPanel bHome;
    private javax.swing.JPanel bSair;
    private javax.swing.JPanel bSobre;
    private javax.swing.JLabel background;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbProdutos;
    // End of variables declaration//GEN-END:variables


// INÍCIO Método para listar produtos na tabela
    private void listarProdutos() {

        java.sql.Connection con = ConnectionFactory.getConnection();
        PreparedStatement stmt = null;
        ResultSet rs = null;

        String sql = "SELECT estoque Estoque, produto Produto,codigo_produto Código  , valor Valor_R$ from produtos  ORDER BY estoque";
        try {
            stmt = con.prepareStatement(sql);
            rs = rs = stmt.executeQuery();

            tbProdutos.setModel(DbUtils.resultSetToTableModel(rs));

            tbProdutos.setDefaultEditor(Object.class, null);

            tbProdutos.getColumnModel().getColumn(0).setPreferredWidth(5);
            tbProdutos.getColumnModel().getColumn(1).setPreferredWidth(350);
            tbProdutos.getColumnModel().getColumn(2).setPreferredWidth(20);
            tbProdutos.getColumnModel().getColumn(3).setPreferredWidth(20);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            ConnectionFactory.closeConnection(con, stmt);
        }

    }
    // FIM Método para listar produtos na tabela
    
    // INÍCIO Método para setar icon do jFrame
    private void setaricon() {

        //  ImageIcon frameIcon = new ImageIcon("icon.png");
        //this.setIconImage(frameIcon.getImage());
        URL url = this.getClass().getResource("icon.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
    }
    // FIM Método para setar icon do jFrame

}
