/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import dao.ConnectionFactory;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author IdeaSofist
 */
public class ViewAcessoCadastroUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form ViewAcesso
     */
    public ViewAcessoCadastroUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tLogin = new javax.swing.JTextField();
        tSenha = new javax.swing.JPasswordField();
        bEntrar = new javax.swing.JPanel();
        bSair = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setType(java.awt.Window.Type.UTILITY);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tLogin.setBorder(null);
        tLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tLoginKeyReleased(evt);
            }
        });
        getContentPane().add(tLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 270, 23));

        tSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tSenha.setBorder(null);
        tSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tSenhaKeyReleased(evt);
            }
        });
        getContentPane().add(tSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 270, 23));

        bEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bEntrar.setOpaque(false);
        bEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bEntrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bEntrarLayout = new javax.swing.GroupLayout(bEntrar);
        bEntrar.setLayout(bEntrarLayout);
        bEntrarLayout.setHorizontalGroup(
            bEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        bEntrarLayout.setVerticalGroup(
            bEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(bEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 483, 250, 40));

        bSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bSair.setOpaque(false);
        bSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSairMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bSairLayout = new javax.swing.GroupLayout(bSair);
        bSair.setLayout(bSairLayout);
        bSairLayout.setHorizontalGroup(
            bSairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        bSairLayout.setVerticalGroup(
            bSairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(bSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 40, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TelaLiberarAcesso.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSairMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_bSairMouseClicked

    private void bEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bEntrarMouseClicked
        // TODO add your handling code here:
        liberarAcesso();
    }//GEN-LAST:event_bEntrarMouseClicked

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
             liberarAcesso();
         }
    }//GEN-LAST:event_formKeyReleased

    private void tLoginKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tLoginKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
             liberarAcesso();
         }
    }//GEN-LAST:event_tLoginKeyReleased

    private void tSenhaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tSenhaKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
             liberarAcesso();
         }
    }//GEN-LAST:event_tSenhaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAcessoCadastroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAcessoCadastroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAcessoCadastroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAcessoCadastroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAcessoCadastroUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bEntrar;
    private javax.swing.JPanel bSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField tLogin;
    private javax.swing.JPasswordField tSenha;
    // End of variables declaration//GEN-END:variables

// INICIO Método para liberar acesso administrativo
 private void liberarAcesso() {

        java.sql.Connection con = ConnectionFactory.getConnection();
        PreparedStatement stmt = null;
        ResultSet rs = null;

        String sql = "select * from usuarios where login=? and senha =? ";
        try {
            stmt = con.prepareStatement(sql);
            stmt.setString(1, tLogin.getText());
            stmt.setString(2, tSenha.getText());
            rs = stmt.executeQuery();

            if (rs.next()) {
                String perfil = rs.getString(6);
                if (perfil.equals("Administrador")) {

                    ViewCadastroUsuarios usuarios = new ViewCadastroUsuarios();
                    usuarios.setVisible(true);

                    

                    this.dispose();
                } else {
                     JOptionPane.showMessageDialog(null, "Acesso Permitido apenas para Administrador!", "Atençao!", JOptionPane.WARNING_MESSAGE);
                    this.dispose();

                }
            } else {
                JOptionPane.showMessageDialog(null, "Login ou Senha Inválido(s)!", "Atençao!", JOptionPane.WARNING_MESSAGE);
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Falha ao conectar com banco de dados! \n" + e, "Atençao!", JOptionPane.ERROR_MESSAGE);
        } finally {
            ConnectionFactory.closeConnection(con, stmt);
        }

    }
 // FIM Método para liberar acesso administrativo


}
