/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import dao.ConnectionFactory;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author IdeaSofist
 */
public class ViewCadastroProdutos extends javax.swing.JFrame {

    /**
     * Creates new form ViewCadastroProdutos
     */
    
    // Variáveis uteis
    private String salvar_alterar = "salvar";
    private String codigo_produto = null;
    NumberFormat formatarDouble = new DecimalFormat("0.00");
    
    
    
    public ViewCadastroProdutos() {
        initComponents();
        listarProdutos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tProduto = new javax.swing.JTextField();
        tValor = new javax.swing.JTextField();
        tEstoque = new javax.swing.JSpinner();
        bSalvar = new javax.swing.JPanel();
        bAlterar = new javax.swing.JPanel();
        bExcluir = new javax.swing.JPanel();
        bLimpar = new javax.swing.JPanel();
        bSair = new javax.swing.JPanel();
        tPesquisar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProdutos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tProduto.setBackground(new java.awt.Color(48, 48, 74));
        tProduto.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        tProduto.setForeground(new java.awt.Color(255, 255, 255));
        tProduto.setBorder(null);
        tProduto.setOpaque(false);
        getContentPane().add(tProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 520, -1));

        tValor.setBackground(new java.awt.Color(48, 48, 74));
        tValor.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        tValor.setForeground(new java.awt.Color(255, 255, 255));
        tValor.setText("00,00");
        tValor.setBorder(null);
        tValor.setOpaque(false);
        getContentPane().add(tValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 446, 520, -1));

        tEstoque.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        tEstoque.setModel(new javax.swing.SpinnerNumberModel());
        getContentPane().add(tEstoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 395, 60, -1));

        bSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bSalvar.setOpaque(false);
        bSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSalvarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bSalvarLayout = new javax.swing.GroupLayout(bSalvar);
        bSalvar.setLayout(bSalvarLayout);
        bSalvarLayout.setHorizontalGroup(
            bSalvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        bSalvarLayout.setVerticalGroup(
            bSalvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(bSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 495, 140, 40));

        bAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bAlterar.setOpaque(false);
        bAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bAlterarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bAlterarLayout = new javax.swing.GroupLayout(bAlterar);
        bAlterar.setLayout(bAlterarLayout);
        bAlterarLayout.setHorizontalGroup(
            bAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        bAlterarLayout.setVerticalGroup(
            bAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(bAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 495, 140, 40));

        bExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bExcluir.setOpaque(false);
        bExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bExcluirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bExcluirLayout = new javax.swing.GroupLayout(bExcluir);
        bExcluir.setLayout(bExcluirLayout);
        bExcluirLayout.setHorizontalGroup(
            bExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        bExcluirLayout.setVerticalGroup(
            bExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(bExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 495, 140, 40));

        bLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bLimpar.setOpaque(false);
        bLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bLimparMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bLimparLayout = new javax.swing.GroupLayout(bLimpar);
        bLimpar.setLayout(bLimparLayout);
        bLimparLayout.setHorizontalGroup(
            bLimparLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        bLimparLayout.setVerticalGroup(
            bLimparLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(bLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 495, 160, 40));

        bSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bSair.setOpaque(false);
        bSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSairMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bSairLayout = new javax.swing.GroupLayout(bSair);
        bSair.setLayout(bSairLayout);
        bSairLayout.setHorizontalGroup(
            bSairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        bSairLayout.setVerticalGroup(
            bSairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(bSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 500, 40, 50));

        tPesquisar.setBackground(new java.awt.Color(48, 48, 74));
        tPesquisar.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        tPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        tPesquisar.setBorder(null);
        tPesquisar.setOpaque(false);
        tPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tPesquisarKeyReleased(evt);
            }
        });
        getContentPane().add(tPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 45, 275, -1));

        tbProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbProdutos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 980, 180));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TelaCadastroProdutos.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSairMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_bSairMouseClicked

    private void bSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSalvarMouseClicked
        // TODO add your handling code here:
        // Validar campos antes de chamar o método para salvar
        if ((tProduto.getText().isEmpty()) || (tEstoque.getValue().toString().isEmpty()) || (tValor.getText().isEmpty()) || (tValor.getText().equals("00,00"))) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!" , "Atençao!" ,JOptionPane.WARNING_MESSAGE);
        } else {
            if (salvar_alterar == "salvar") {
                salvarProduto();
                listarProdutos();
                //limparFormulario();
            } else {
                alterar();
                listarProdutos();
            }

        }
    }//GEN-LAST:event_bSalvarMouseClicked

    private void bAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAlterarMouseClicked
        // TODO add your handling code here:
        
        preparar_alterar();
    }//GEN-LAST:event_bAlterarMouseClicked

    private void bExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bExcluirMouseClicked
        // TODO add your handling code here:
        
        if (codigo_produto == null) {
            JOptionPane.showMessageDialog(null, "Selecione um Produto!" , "Atençao!" ,JOptionPane.WARNING_MESSAGE);
        } else {
            excluir();
            limparFormulario();
        }
    }//GEN-LAST:event_bExcluirMouseClicked

    private void bLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLimparMouseClicked
        // TODO add your handling code here:
         limparFormulario();
    }//GEN-LAST:event_bLimparMouseClicked

    private void tPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tPesquisarKeyReleased
        // TODO add your handling code here:
        pesquisarProduto();
    }//GEN-LAST:event_tPesquisarKeyReleased

    private void tbProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbProdutosMouseClicked
        // TODO add your handling code here:
        setar_campos();
    }//GEN-LAST:event_tbProdutosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCadastroProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bAlterar;
    private javax.swing.JPanel bExcluir;
    private javax.swing.JPanel bLimpar;
    private javax.swing.JPanel bSair;
    private javax.swing.JPanel bSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner tEstoque;
    private javax.swing.JTextField tPesquisar;
    private javax.swing.JTextField tProduto;
    private javax.swing.JTextField tValor;
    private javax.swing.JTable tbProdutos;
    // End of variables declaration//GEN-END:variables



    /*
    *
    * ÁREA PARA TODOS OS MÉTODOS
    *
     */
    
    
     // INÍCIO Método para setar icon do jFrame
    private void setaricon() {

        //  ImageIcon frameIcon = new ImageIcon("icon.png");
        //this.setIconImage(frameIcon.getImage());
        URL url = this.getClass().getResource("icon.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
    }
    // FIM Método para setar icon do jFrame
    
    
    //INÍCIO Método para salvar produtos
    private void salvarProduto() {

        java.sql.Connection con = ConnectionFactory.getConnection();
        PreparedStatement stmt = null;

        String sql = "INSERT  INTO produtos "
                + "( produto, "
                + "estoque,   "
                + "valor  ) "
                + " VALUES (?,?,? )";
        try {
            stmt = con.prepareStatement(sql);

            stmt.setString(1, tProduto.getText());
            stmt.setString(2, tEstoque.getValue().toString());
            stmt.setString(3, tValor.getText().replace(",", "."));

            // A linha abaixo atualiza os dados     
            int adicionado = stmt.executeUpdate();

            if (adicionado > 0) {
                JOptionPane.showMessageDialog(null, "Produto cadastrado com sucesso!");
                listarProdutos();
                limparFormulario();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Falha ao cadastrar Produto " + "\n" + e , "Atençao!" ,JOptionPane.ERROR_MESSAGE);
        } finally {
            ConnectionFactory.closeConnection(con, stmt);
        }
    }
    //FIM Método para salvar produtos

    // INÍCIO Método para limpar formulário
    private void limparFormulario() {

        salvar_alterar = "salvar";
        codigo_produto = null;

        tPesquisar.setText(null);
        tProduto.setText(null);
        tEstoque.setValue(0);
        tValor.setText("00,00");
        bExcluir.setEnabled(false);
        bAlterar.setEnabled(false);
    }
    // FIM Método para limpar formulário

    // INÍCIO Método para listar produtos na tabela
    private void listarProdutos() {

        java.sql.Connection con = ConnectionFactory.getConnection();
        PreparedStatement stmt = null;
        ResultSet rs = null;

        String sql = "SELECT codigo_produto Código, produto Produto, estoque Estoque , valor Valor_R$ from produtos ";
        try {
            stmt = con.prepareStatement(sql);
            rs = rs = stmt.executeQuery();

            tbProdutos.setModel(DbUtils.resultSetToTableModel(rs));

            tbProdutos.setDefaultEditor(Object.class, null);

            tbProdutos.getColumnModel().getColumn(0).setPreferredWidth(5);
            tbProdutos.getColumnModel().getColumn(1).setPreferredWidth(350);
            tbProdutos.getColumnModel().getColumn(2).setPreferredWidth(20);
            tbProdutos.getColumnModel().getColumn(3).setPreferredWidth(20);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            ConnectionFactory.closeConnection(con, stmt);
        }

    }
    // FIM Método para listar produtos na tabela

    // INÍCIO Método para setar campos para alterar dados de produto
    public void preparar_alterar() {

        salvar_alterar = "Alterar";

        int setar = tbProdutos.getSelectedRow();
        codigo_produto = tbProdutos.getModel().getValueAt(setar, 0).toString();
        // tId.setText(tbUsuarios.getModel().getValueAt(setar, 0).toString());
        tProduto.setText(tbProdutos.getModel().getValueAt(setar, 1).toString());
        tEstoque.setValue(tbProdutos.getModel().getValueAt(setar, 2));
        tValor.setText(tbProdutos.getModel().getValueAt(setar, 3).toString());

    }
    // FIM Método para setar campos para alterar dados de produto

    // INÍCIO Método para setar codigo de produto selecionado para alterar ou excluir
    public void setar_campos() {
        int setar = tbProdutos.getSelectedRow();
        codigo_produto = tbProdutos.getModel().getValueAt(setar, 0).toString();
        bExcluir.setEnabled(true);
        bAlterar.setEnabled(true);

    }
    // FIM Método para setar id de usuário para alterar ou excluir

    // INÍCIO Método para alterar dados de produto
    private void alterar() {

        java.sql.Connection con = ConnectionFactory.getConnection();
        PreparedStatement stmt = null;
        ResultSet rs = null;

        String sql = "UPDATE produtos SET "
                + "produto =? ,"
                + "estoque =? , "
                + "valor =?  "
                + " WHERE codigo_produto =? ";
        try {
            stmt = con.prepareStatement(sql);
            stmt.setString(1, tProduto.getText());
            stmt.setString(2, tEstoque.getValue().toString());
            stmt.setString(3, tValor.getText().replace(",", "."));

            stmt.setString(4, codigo_produto);

            //   pst.setString(6,txtIdCli.getText());
            if ((tProduto.getText().isEmpty()) || (tEstoque.getValue().toString().isEmpty()) || (tValor.getText().isEmpty()) || (tValor.getText().equals("00,00"))) {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos!" , "Atençao!" ,JOptionPane.WARNING_MESSAGE);
            } else {

                // A linha abaixo atualiza os dados     
                int adicionado = stmt.executeUpdate();
                if (adicionado > 0) {
                    JOptionPane.showMessageDialog(null, "Dados de Produto atualizados com sucesso!");
                    listarProdutos();
                    limparFormulario();

                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            ConnectionFactory.closeConnection(con, stmt);
        }
    }
    // FIM Método para alterar dados de produto

    //INÍCIO Método para Excluír Produto
    private void excluir() {

        java.sql.Connection con = ConnectionFactory.getConnection();
        PreparedStatement stmt = null;
        ResultSet rs = null;

        int confirma = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja Excluir este Produto?", "Atenção!", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {

            String sql = "DELETE FROM produtos where codigo_produto =?";
            try {
                stmt = con.prepareStatement(sql);
                stmt.setString(1, codigo_produto);
                int apagado = stmt.executeUpdate();
                if (apagado > 0) {
                    JOptionPane.showMessageDialog(null, "Produto excluído com sucesso!");
                    listarProdutos();
                    limparFormulario();

                }

            } catch (java.sql.SQLIntegrityConstraintViolationException e) {
                JOptionPane.showMessageDialog(null, "Produto não pode ser excluído!" , "Atençao!" ,JOptionPane.ERROR_MESSAGE);
            } catch (Exception ee) {
                JOptionPane.showMessageDialog(null, ee);
                System.out.println(ee);
            } finally {
                ConnectionFactory.closeConnection(con, stmt);
            }

        }

    }
    //FIM Método para Excluír Produto

    //INÍCIO Método para pesquisar Produto por codigo ou produto
    private void pesquisarProduto() {
        java.sql.Connection con = ConnectionFactory.getConnection();
        PreparedStatement stmt = null;
        ResultSet rs = null;

        String sql = "SELECT codigo_produto Código, "
                + "produto Produto,"
                + " estoque Estoque , "
                + "valor Valor_R$ from produtos  "
                + "WHERE  produto  LIKE ? OR codigo_produto LIKE ? ";

        try {

            stmt = con.prepareStatement(sql);
            stmt.setString(1, tPesquisar.getText() + "%");
            stmt.setString(2, tPesquisar.getText() + "%");
            rs = stmt.executeQuery();

            // Usar a biblioteca *rs2xml* para listar dados
            tbProdutos.setModel(DbUtils.resultSetToTableModel(rs));

            tbProdutos.setDefaultEditor(Object.class, null);

            tbProdutos.getColumnModel().getColumn(0).setPreferredWidth(5);
            tbProdutos.getColumnModel().getColumn(1).setPreferredWidth(350);
            tbProdutos.getColumnModel().getColumn(2).setPreferredWidth(20);
            tbProdutos.getColumnModel().getColumn(3).setPreferredWidth(20);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            ConnectionFactory.closeConnection(con, stmt);
        }
    }
    //FIM Método para pesquisar Produto por codigo ou produto



}
