/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import dao.ConnectionFactory;
import java.awt.Image;
import java.net.URL;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author IdeaSofist
 */
public class ViewCadastroUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form ViewCadastroUsuarios
     */
    
    private String salvar_alterar = "salvar";
    private String id = null;
    
    
    public ViewCadastroUsuarios() {
        initComponents();
        listarUsuarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tNome = new javax.swing.JTextField();
        tLogin = new javax.swing.JTextField();
        cbPerfil = new javax.swing.JComboBox<>();
        tSenha = new javax.swing.JPasswordField();
        tPesquisar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbUsuarios = new javax.swing.JTable();
        bSalvar = new javax.swing.JPanel();
        bAlterar = new javax.swing.JPanel();
        bExcluir = new javax.swing.JPanel();
        bLimpar = new javax.swing.JPanel();
        bSair = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tNome.setBackground(new java.awt.Color(47, 47, 73));
        tNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tNome.setForeground(new java.awt.Color(255, 255, 255));
        tNome.setBorder(null);
        tNome.setOpaque(false);
        getContentPane().add(tNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 330, -1));

        tLogin.setBackground(new java.awt.Color(47, 47, 73));
        tLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tLogin.setForeground(new java.awt.Color(255, 255, 255));
        tLogin.setToolTipText("");
        tLogin.setBorder(null);
        tLogin.setOpaque(false);
        getContentPane().add(tLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 395, 330, -1));

        cbPerfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selecione--", "Administrador", "Usuário" }));
        getContentPane().add(cbPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 348, 220, -1));

        tSenha.setBackground(new java.awt.Color(47, 47, 73));
        tSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tSenha.setForeground(new java.awt.Color(255, 255, 255));
        tSenha.setBorder(null);
        tSenha.setOpaque(false);
        getContentPane().add(tSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 398, 220, -1));

        tPesquisar.setBackground(new java.awt.Color(47, 47, 73));
        tPesquisar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        tPesquisar.setBorder(null);
        tPesquisar.setOpaque(false);
        tPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tPesquisarKeyReleased(evt);
            }
        });
        getContentPane().add(tPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 47, 275, -1));

        tbUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbUsuarios);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 980, 190));

        bSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bSalvar.setOpaque(false);
        bSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSalvarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bSalvarLayout = new javax.swing.GroupLayout(bSalvar);
        bSalvar.setLayout(bSalvarLayout);
        bSalvarLayout.setHorizontalGroup(
            bSalvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 133, Short.MAX_VALUE)
        );
        bSalvarLayout.setVerticalGroup(
            bSalvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        getContentPane().add(bSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 495, 133, 38));

        bAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bAlterar.setOpaque(false);
        bAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bAlterarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bAlterarLayout = new javax.swing.GroupLayout(bAlterar);
        bAlterar.setLayout(bAlterarLayout);
        bAlterarLayout.setHorizontalGroup(
            bAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        bAlterarLayout.setVerticalGroup(
            bAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        getContentPane().add(bAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 495, 140, 38));

        bExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bExcluir.setOpaque(false);
        bExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bExcluirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bExcluirLayout = new javax.swing.GroupLayout(bExcluir);
        bExcluir.setLayout(bExcluirLayout);
        bExcluirLayout.setHorizontalGroup(
            bExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        bExcluirLayout.setVerticalGroup(
            bExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        getContentPane().add(bExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 495, 130, 38));

        bLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bLimpar.setOpaque(false);
        bLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bLimparMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bLimparLayout = new javax.swing.GroupLayout(bLimpar);
        bLimpar.setLayout(bLimparLayout);
        bLimparLayout.setHorizontalGroup(
            bLimparLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 155, Short.MAX_VALUE)
        );
        bLimparLayout.setVerticalGroup(
            bLimparLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        getContentPane().add(bLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 495, 155, 38));

        bSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bSair.setOpaque(false);
        bSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSairMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bSairLayout = new javax.swing.GroupLayout(bSair);
        bSair.setLayout(bSairLayout);
        bSairLayout.setHorizontalGroup(
            bSairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );
        bSairLayout.setVerticalGroup(
            bSairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(bSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 505, 37, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TelaCadastroUsuarios.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSairMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_bSairMouseClicked

    private void tPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tPesquisarKeyReleased
        // TODO add your handling code here:
         pesquisarUsuario();
    }//GEN-LAST:event_tPesquisarKeyReleased

    private void tbUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbUsuariosMouseClicked
        // TODO add your handling code here:
        setar_campos();
    }//GEN-LAST:event_tbUsuariosMouseClicked

    private void bSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSalvarMouseClicked
        // TODO add your handling code here:
        // Validar campos antes de chamar o método para salvar
          if ((tNome.getText().isEmpty()) || (tLogin.getText().isEmpty()) || (tSenha.getText().isEmpty()) || (cbPerfil.getSelectedItem().toString().equals("--Selecione--"))) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!" , "Atençao!" ,JOptionPane.WARNING_MESSAGE);
        } else {
            if (salvar_alterar == "salvar") {
                salvarUsuario();
                listarUsuarios();
                //limparFormulario();
            } else {
                alterar();
                listarUsuarios();
            }

        }   
    }//GEN-LAST:event_bSalvarMouseClicked

    private void bAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAlterarMouseClicked
        // TODO add your handling code here:
          preparar_alterar();
    }//GEN-LAST:event_bAlterarMouseClicked

    private void bExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bExcluirMouseClicked
        // TODO add your handling code here:
        if (id == null) {
            JOptionPane.showMessageDialog(null, "Selecione um Usuário!" , "Atençao!" ,JOptionPane.WARNING_MESSAGE);
        } else {
            excluir();
            limparFormulario();
        }
    }//GEN-LAST:event_bExcluirMouseClicked

    private void bLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLimparMouseClicked
        // TODO add your handling code here:
         limparFormulario();
    }//GEN-LAST:event_bLimparMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCadastroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCadastroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCadastroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCadastroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCadastroUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bAlterar;
    private javax.swing.JPanel bExcluir;
    private javax.swing.JPanel bLimpar;
    private javax.swing.JPanel bSair;
    private javax.swing.JPanel bSalvar;
    private javax.swing.JComboBox<String> cbPerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tLogin;
    private javax.swing.JTextField tNome;
    private javax.swing.JTextField tPesquisar;
    private javax.swing.JPasswordField tSenha;
    private javax.swing.JTable tbUsuarios;
    // End of variables declaration//GEN-END:variables



    /*
    *
    * ÁREA PARA TODOS OS MÉTODOS
    *
     */
    
      
    
    
    // Início Método para salvar um Usuário
    private void salvarUsuario() {

        java.sql.Connection con = ConnectionFactory.getConnection();
        PreparedStatement stmt = null;
        ResultSet rs = null;

        String sql = "INSERT  INTO usuarios "
                + "( nome, "
                + "login,   "
                + "senha, "
                + "perfil ) "
                + " VALUES (?,?,?,?)";
        try {
            stmt = con.prepareStatement(sql);

            stmt.setString(1, tNome.getText());
            stmt.setString(2, tLogin.getText());
            stmt.setString(3, tSenha.getText());
            stmt.setString(4, cbPerfil.getSelectedItem().toString());

            // A linha abaixo atualiza os dados     
            int adicionado = stmt.executeUpdate();

            if (adicionado > 0) {
                JOptionPane.showMessageDialog(null, "Usuário cadastrado com sucesso!");
                listarUsuarios();
                limparFormulario();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Falha ao cadastrar Usuário " + "\n" + e , "Atençao!" ,JOptionPane.ERROR_MESSAGE );
        } finally {
            ConnectionFactory.closeConnection(con, stmt);
        }
    }
    // Fim Método para salvar um Usuário

    // INÍCIO Método para listar usuários na tabela
    public void listarUsuarios() {

        java.sql.Connection con = ConnectionFactory.getConnection();
        PreparedStatement stmt = null;
        ResultSet rs = null;

        String sql = "SELECT idusuarios ID, nome Nome, login Login , senha Senha, perfil Perfil from usuarios ";
        try {
            stmt = con.prepareStatement(sql);
            rs = rs = stmt.executeQuery();

            tbUsuarios.setModel(DbUtils.resultSetToTableModel(rs));

            tbUsuarios.setDefaultEditor(Object.class, null);

            tbUsuarios.getColumnModel().getColumn(0).setPreferredWidth(10);
            tbUsuarios.getColumnModel().getColumn(1).setPreferredWidth(250);
            tbUsuarios.getColumnModel().getColumn(2).setPreferredWidth(150);
            tbUsuarios.getColumnModel().getColumn(3).setPreferredWidth(150);
            tbUsuarios.getColumnModel().getColumn(4).setPreferredWidth(100);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            ConnectionFactory.closeConnection(con, stmt);
        }
    }
    // FIM Método para listar usuários na tabela

    // INÍCIO Método para setar campos para alterar dados de usuário
    public void preparar_alterar() {

        salvar_alterar = "Alterar";

        

            int setar = tbUsuarios.getSelectedRow();
             id = tbUsuarios.getModel().getValueAt(setar, 0).toString();
          // tId.setText(tbUsuarios.getModel().getValueAt(setar, 0).toString());
            tNome.setText(tbUsuarios.getModel().getValueAt(setar, 1).toString());
            tLogin.setText(tbUsuarios.getModel().getValueAt(setar, 2).toString());
            tSenha.setText(tbUsuarios.getModel().getValueAt(setar, 3).toString());
            cbPerfil.setSelectedItem(tbUsuarios.getModel().getValueAt(setar, 4).toString());
          
    }
    // FIM Método para setar campos para alterar dados de usuário

    
    
    // INÍCIO Método para setar id de usuário para alterar ou excluir
    public void setar_campos() {
        int setar = tbUsuarios.getSelectedRow();
        id = tbUsuarios.getModel().getValueAt(setar, 0).toString();
         
   
    }
    // FIM Método para setar id de usuário para alterar ou excluir

    
    
    // INÍCIO Método para alterar dados de usuário
    private void alterar() {

        java.sql.Connection con = ConnectionFactory.getConnection();
        PreparedStatement stmt = null;
        ResultSet rs = null;

        String sql = "UPDATE usuarios SET "
                + "nome =? ,"
                + "login =? , "
                + "senha =? , "
                + "perfil =? "
                + " WHERE idusuarios =? ";
        try {
            stmt = con.prepareStatement(sql);
            stmt.setString(1, tNome.getText());
            stmt.setString(2, tLogin.getText());
            stmt.setString(3, tSenha.getText());
            stmt.setString(4, cbPerfil.getSelectedItem().toString());

            stmt.setString(5, id);

            //   pst.setString(6,txtIdCli.getText());
            if ((tNome.getText().isEmpty()) || (tLogin.getText().isEmpty()) || (tSenha.getText().isEmpty()) || (cbPerfil.getSelectedItem().toString().equals("--Selecione--"))) {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos!" , "Atençao!" ,JOptionPane.WARNING_MESSAGE);
            } else {

                // A linha abaixo atualiza os dados     
                int adicionado = stmt.executeUpdate();
                if (adicionado > 0) {
                    JOptionPane.showMessageDialog(null, "Dados de Usuário alterados com sucesso!");
                    listarUsuarios();
                    limparFormulario();

                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            ConnectionFactory.closeConnection(con, stmt);
        }
    }
    // FIM Método para alterar dados de usuário

    //INÍCIO Método para limpar campos
    private void limparFormulario() {
        
        salvar_alterar = "salvar";
         id = null;
        
        tNome.setText(null);
        tLogin.setText(null);
        tSenha.setText(null);
        cbPerfil.setSelectedItem("--Selecione--");
         
    }
    //FIM Método para limpar campos

    //INÍCIO Método para Excluír Usuário
    private void excluir() {

        java.sql.Connection con = ConnectionFactory.getConnection();
        PreparedStatement stmt = null;
        ResultSet rs = null;

        int confirma = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja Excluir este Usuário?", "Atenção!", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {

            String sql = "DELETE FROM usuarios where idusuarios =?";
            try {
                stmt = con.prepareStatement(sql);
                stmt.setString(1, id);
                int apagado = stmt.executeUpdate();
                if (apagado > 0) {
                    JOptionPane.showMessageDialog(null, "Usuário excluído com sucesso!");
                    listarUsuarios();
                    limparFormulario();

                }

            } catch (java.sql.SQLIntegrityConstraintViolationException e) {
                JOptionPane.showMessageDialog(null, "Usuário não pode ser excluído!" , "Atençao!" ,JOptionPane.ERROR_MESSAGE);
            } catch (Exception ee) {
                JOptionPane.showMessageDialog(null, ee);
                System.out.println(ee);
            } finally {
            ConnectionFactory.closeConnection(con, stmt);
        }

        }

    }
    //FIM Método para Excluír Usuário
    
    
    
    //INÍCIO Método para pesquisar Usuário por Id ou Nome
    private void pesquisarUsuario() {
        java.sql.Connection con = ConnectionFactory.getConnection();
        PreparedStatement stmt = null;
        ResultSet rs = null;

        String sql = "SELECT idusuarios ID, nome Nome, login Login , senha Senha, perfil Nivel  "
                + " FROM usuarios WHERE nome    LIKE ? OR idusuarios LIKE ? ";

        try {

            stmt = con.prepareStatement(sql);
            stmt.setString(1, tPesquisar.getText() + "%");
            stmt.setString(2, tPesquisar.getText() + "%");
            rs = stmt.executeQuery();

            // Usar a biblioteca *rs2xml* para listar dados
            tbUsuarios.setModel(DbUtils.resultSetToTableModel(rs));
            
            tbUsuarios.getColumnModel().getColumn(0).setPreferredWidth(10);
            tbUsuarios.getColumnModel().getColumn(1).setPreferredWidth(250);
            tbUsuarios.getColumnModel().getColumn(2).setPreferredWidth(150);
            tbUsuarios.getColumnModel().getColumn(3).setPreferredWidth(150);
            tbUsuarios.getColumnModel().getColumn(4).setPreferredWidth(100);
            

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            ConnectionFactory.closeConnection(con, stmt);
        }
    }
    //FIM Método para pesquisar Usuário por Id ou Nome




}
